baseurl: http://new.eightypercent.net:81/
languageCode: en-us
title: 80%
description: The personal blog of Joe Beda
uglyurls: true
pluralizelisttitles: false
paginate: 10

taxonomies:
  archive: Archive

params:
  description: "The personal blog of Joe Beda"